version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: apache-php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground" # Instala mysqli e inicia o Apache
    networks:
      - lamp-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge
